################################################################################
# libretro-mgba
################################################################################

LIBRETRO_MGBA_VERSION = local
LIBRETRO_MGBA_SITE = $(BR2_EXTERNAL_ALLIUM_EXTERNAL_PATH)/package/libretro-mgba
LIBRETRO_MGBA_SITE_METHOD = local
LIBRETRO_MGBA_LICENSE = See upstream

LIBRETRO_MGBA_CORES_WORKDIR = $(@D)/core-build
LIBRETRO_MGBA_CORES_INSTALL_DIR = /usr/lib/minui/cores

LIBRETRO_MGBA_BUILD_HELPER = $(BR2_EXTERNAL_ALLIUM_EXTERNAL_PATH)/package/allium-support/libretro-core.mkfrag
LIBRETRO_MGBA_CORE_NAME = mgba
LIBRETRO_MGBA_CORE_REPO = 
LIBRETRO_MGBA_CORE_BRANCH = 
LIBRETRO_MGBA_CORE_HASH = 
LIBRETRO_MGBA_CORE_MAKEFILE = 
LIBRETRO_MGBA_CORE_BUILD_PATH = 
LIBRETRO_MGBA_CORE_OUTPUT_NAME = mgba_libretro.so
LIBRETRO_MGBA_CORE_PLATFORM = unix
LIBRETRO_MGBA_CORE_EXTRA_VARS = 

define LIBRETRO_MGBA_BUILD_CMDS
	$(TARGET_MAKE_ENV) env -u GIT_DIR $(MAKE1) -f $(LIBRETRO_MGBA_BUILD_HELPER) \
		WORKDIR="$(LIBRETRO_MGBA_CORES_WORKDIR)" \
		PATCH_DIR="$(@D)/patches" \
		CORE_NAME="$(LIBRETRO_MGBA_CORE_NAME)" \
		CORE_REPO="$(LIBRETRO_MGBA_CORE_REPO)" \
		CORE_BRANCH="$(LIBRETRO_MGBA_CORE_BRANCH)" \
		CORE_HASH="$(LIBRETRO_MGBA_CORE_HASH)" \
		CORE_MAKEFILE="$(LIBRETRO_MGBA_CORE_MAKEFILE)" \
		CORE_BUILD_PATH="$(LIBRETRO_MGBA_CORE_BUILD_PATH)" \
		CORE_OUTPUT_NAME="$(LIBRETRO_MGBA_CORE_OUTPUT_NAME)" \
		CORE_PLATFORM="$(LIBRETRO_MGBA_CORE_PLATFORM)" \
		CORE_EXTRA_VARS="$(LIBRETRO_MGBA_CORE_EXTRA_VARS)" \
		CC="$(TARGET_CC)" \
		CXX="$(TARGET_CXX)" \
		AR="$(TARGET_AR)" \
		RANLIB="$(TARGET_RANLIB)" \
		CROSS_COMPILE="$(TARGET_CROSS)" \
		build
endef
define LIBRETRO_MGBA_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 0755 \
		$(LIBRETRO_MGBA_CORES_WORKDIR)/output/mgba_libretro.so \
		$(TARGET_DIR)$(LIBRETRO_MGBA_CORES_INSTALL_DIR)/mgba_libretro.so
endef

$(eval $(generic-package))
