################################################################################
# libretro-fake08
################################################################################

LIBRETRO_FAKE08_VERSION = local
LIBRETRO_FAKE08_SITE = $(BR2_EXTERNAL_ALLIUM_EXTERNAL_PATH)/package/libretro-fake08
LIBRETRO_FAKE08_SITE_METHOD = local
LIBRETRO_FAKE08_LICENSE = See upstream

LIBRETRO_FAKE08_CORES_WORKDIR = $(@D)/core-build
LIBRETRO_FAKE08_CORES_INSTALL_DIR = /usr/lib/minui/cores

LIBRETRO_FAKE08_BUILD_HELPER = $(BR2_EXTERNAL_ALLIUM_EXTERNAL_PATH)/package/allium-support/libretro-core.mkfrag
LIBRETRO_FAKE08_CORE_NAME = fake-08
LIBRETRO_FAKE08_CORE_REPO = https://github.com/jtothebell/fake-08
LIBRETRO_FAKE08_CORE_BRANCH =
LIBRETRO_FAKE08_CORE_HASH =
LIBRETRO_FAKE08_CORE_MAKEFILE =
LIBRETRO_FAKE08_CORE_BUILD_PATH = fake-08/platform/libretro
LIBRETRO_FAKE08_CORE_OUTPUT_NAME = fake08_libretro.so
LIBRETRO_FAKE08_CORE_PLATFORM = unix
LIBRETRO_FAKE08_CORE_EXTRA_VARS =

define LIBRETRO_FAKE08_BUILD_CMDS
	$(TARGET_MAKE_ENV) env -u GIT_DIR $(MAKE1) -f $(LIBRETRO_FAKE08_BUILD_HELPER) \
		WORKDIR="$(LIBRETRO_FAKE08_CORES_WORKDIR)" \
		PATCH_DIR="$(@D)/patches" \
		CORE_NAME="$(LIBRETRO_FAKE08_CORE_NAME)" \
		CORE_REPO="$(LIBRETRO_FAKE08_CORE_REPO)" \
		CORE_BRANCH="$(LIBRETRO_FAKE08_CORE_BRANCH)" \
		CORE_HASH="$(LIBRETRO_FAKE08_CORE_HASH)" \
		CORE_MAKEFILE="$(LIBRETRO_FAKE08_CORE_MAKEFILE)" \
		CORE_BUILD_PATH="$(LIBRETRO_FAKE08_CORE_BUILD_PATH)" \
		CORE_OUTPUT_NAME="$(LIBRETRO_FAKE08_CORE_OUTPUT_NAME)" \
		CORE_PLATFORM="$(LIBRETRO_FAKE08_CORE_PLATFORM)" \
		CORE_EXTRA_VARS="$(LIBRETRO_FAKE08_CORE_EXTRA_VARS)" \
		CC="$(TARGET_CC)" \
		CXX="$(TARGET_CXX)" \
		AR="$(TARGET_AR)" \
		RANLIB="$(TARGET_RANLIB)" \
		CROSS_COMPILE="$(TARGET_CROSS)" \
		build
endef

define LIBRETRO_FAKE08_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 0755 \
		$(LIBRETRO_FAKE08_CORES_WORKDIR)/output/fake-08_libretro.so \
		$(TARGET_DIR)$(LIBRETRO_FAKE08_CORES_INSTALL_DIR)/fake08_libretro.so
endef

$(eval $(generic-package))
