################################################################################
# libretro-picodrive
################################################################################

LIBRETRO_PICODRIVE_VERSION = local
LIBRETRO_PICODRIVE_SITE = $(BR2_EXTERNAL_ALLIUM_EXTERNAL_PATH)/package/libretro-picodrive
LIBRETRO_PICODRIVE_SITE_METHOD = local
LIBRETRO_PICODRIVE_LICENSE = See upstream

LIBRETRO_PICODRIVE_CORES_WORKDIR = $(@D)/core-build
LIBRETRO_PICODRIVE_CORES_INSTALL_DIR = /usr/lib/minui/cores

LIBRETRO_PICODRIVE_BUILD_HELPER = $(BR2_EXTERNAL_ALLIUM_EXTERNAL_PATH)/package/allium-support/libretro-core.mkfrag
LIBRETRO_PICODRIVE_CORE_NAME = picodrive
LIBRETRO_PICODRIVE_CORE_REPO = https://github.com/irixxxx/picodrive
LIBRETRO_PICODRIVE_CORE_BRANCH = 
LIBRETRO_PICODRIVE_CORE_HASH = 
LIBRETRO_PICODRIVE_CORE_MAKEFILE = Makefile.libretro
LIBRETRO_PICODRIVE_CORE_BUILD_PATH = 
LIBRETRO_PICODRIVE_CORE_OUTPUT_NAME = picodrive_libretro.so
LIBRETRO_PICODRIVE_CORE_PLATFORM = aarch64
LIBRETRO_PICODRIVE_CORE_EXTRA_VARS = GIT_DIR= GIT_REVISION=unknown

define LIBRETRO_PICODRIVE_BUILD_CMDS
	$(TARGET_MAKE_ENV) env -u GIT_DIR $(MAKE1) -f $(LIBRETRO_PICODRIVE_BUILD_HELPER) \
		WORKDIR="$(LIBRETRO_PICODRIVE_CORES_WORKDIR)" \
		PATCH_DIR="$(@D)/patches" \
		CORE_NAME="$(LIBRETRO_PICODRIVE_CORE_NAME)" \
		CORE_REPO="$(LIBRETRO_PICODRIVE_CORE_REPO)" \
		CORE_BRANCH="$(LIBRETRO_PICODRIVE_CORE_BRANCH)" \
		CORE_HASH="$(LIBRETRO_PICODRIVE_CORE_HASH)" \
		CORE_MAKEFILE="$(LIBRETRO_PICODRIVE_CORE_MAKEFILE)" \
		CORE_BUILD_PATH="$(LIBRETRO_PICODRIVE_CORE_BUILD_PATH)" \
		CORE_OUTPUT_NAME="$(LIBRETRO_PICODRIVE_CORE_OUTPUT_NAME)" \
		CORE_PLATFORM="$(LIBRETRO_PICODRIVE_CORE_PLATFORM)" \
		CORE_EXTRA_VARS="$(LIBRETRO_PICODRIVE_CORE_EXTRA_VARS)" \
		CC="$(TARGET_CC)" \
		CXX="$(TARGET_CXX)" \
		AR="$(TARGET_AR)" \
		RANLIB="$(TARGET_RANLIB)" \
		CROSS_COMPILE="$(TARGET_CROSS)" \
		build
endef
define LIBRETRO_PICODRIVE_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 0755 \
		$(LIBRETRO_PICODRIVE_CORES_WORKDIR)/output/picodrive_libretro.so \
		$(TARGET_DIR)$(LIBRETRO_PICODRIVE_CORES_INSTALL_DIR)/picodrive_libretro.so
endef

$(eval $(generic-package))
