################################################################################
# libretro-gpsp
################################################################################

LIBRETRO_GPSP_VERSION = local
LIBRETRO_GPSP_SITE = $(BR2_EXTERNAL_ALLIUM_EXTERNAL_PATH)/package/libretro-gpsp
LIBRETRO_GPSP_SITE_METHOD = local
LIBRETRO_GPSP_LICENSE = See upstream

LIBRETRO_GPSP_CORES_WORKDIR = $(@D)/core-build
LIBRETRO_GPSP_CORES_INSTALL_DIR = /usr/lib/minui/cores

LIBRETRO_GPSP_BUILD_HELPER = $(BR2_EXTERNAL_ALLIUM_EXTERNAL_PATH)/package/allium-support/libretro-core.mkfrag
LIBRETRO_GPSP_CORE_NAME = gpsp
LIBRETRO_GPSP_CORE_REPO = 
LIBRETRO_GPSP_CORE_BRANCH = 
LIBRETRO_GPSP_CORE_HASH = 
LIBRETRO_GPSP_CORE_MAKEFILE = 
LIBRETRO_GPSP_CORE_BUILD_PATH = 
LIBRETRO_GPSP_CORE_OUTPUT_NAME = gpsp_libretro.so
LIBRETRO_GPSP_CORE_PLATFORM = arm64
LIBRETRO_GPSP_CORE_EXTRA_VARS = 

define LIBRETRO_GPSP_BUILD_CMDS
	$(TARGET_MAKE_ENV) env -u GIT_DIR $(MAKE1) -f $(LIBRETRO_GPSP_BUILD_HELPER) \
		WORKDIR="$(LIBRETRO_GPSP_CORES_WORKDIR)" \
		PATCH_DIR="$(@D)/patches" \
		CORE_NAME="$(LIBRETRO_GPSP_CORE_NAME)" \
		CORE_REPO="$(LIBRETRO_GPSP_CORE_REPO)" \
		CORE_BRANCH="$(LIBRETRO_GPSP_CORE_BRANCH)" \
		CORE_HASH="$(LIBRETRO_GPSP_CORE_HASH)" \
		CORE_MAKEFILE="$(LIBRETRO_GPSP_CORE_MAKEFILE)" \
		CORE_BUILD_PATH="$(LIBRETRO_GPSP_CORE_BUILD_PATH)" \
		CORE_OUTPUT_NAME="$(LIBRETRO_GPSP_CORE_OUTPUT_NAME)" \
		CORE_PLATFORM="$(LIBRETRO_GPSP_CORE_PLATFORM)" \
		CORE_EXTRA_VARS="$(LIBRETRO_GPSP_CORE_EXTRA_VARS)" \
		CC="$(TARGET_CC)" \
		CXX="$(TARGET_CXX)" \
		AR="$(TARGET_AR)" \
		RANLIB="$(TARGET_RANLIB)" \
		CROSS_COMPILE="$(TARGET_CROSS)" \
		build
endef
define LIBRETRO_GPSP_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 0755 \
		$(LIBRETRO_GPSP_CORES_WORKDIR)/output/gpsp_libretro.so \
		$(TARGET_DIR)$(LIBRETRO_GPSP_CORES_INSTALL_DIR)/gpsp_libretro.so
endef

$(eval $(generic-package))
