################################################################################
# libretro-mednafen-supafaust
################################################################################

LIBRETRO_MEDNAFEN_SUPAFAUST_VERSION = local
LIBRETRO_MEDNAFEN_SUPAFAUST_SITE = $(BR2_EXTERNAL_ALLIUM_EXTERNAL_PATH)/package/libretro-mednafen-supafaust
LIBRETRO_MEDNAFEN_SUPAFAUST_SITE_METHOD = local
LIBRETRO_MEDNAFEN_SUPAFAUST_LICENSE = See upstream

LIBRETRO_MEDNAFEN_SUPAFAUST_CORES_WORKDIR = $(@D)/core-build
LIBRETRO_MEDNAFEN_SUPAFAUST_CORES_INSTALL_DIR = /usr/lib/minui/cores

LIBRETRO_MEDNAFEN_SUPAFAUST_BUILD_HELPER = $(BR2_EXTERNAL_ALLIUM_EXTERNAL_PATH)/package/allium-support/libretro-core.mkfrag
LIBRETRO_MEDNAFEN_SUPAFAUST_CORE_NAME = mednafen_supafaust
LIBRETRO_MEDNAFEN_SUPAFAUST_CORE_REPO = https://github.com/libretro/supafaust
LIBRETRO_MEDNAFEN_SUPAFAUST_CORE_BRANCH = 
LIBRETRO_MEDNAFEN_SUPAFAUST_CORE_HASH = 
LIBRETRO_MEDNAFEN_SUPAFAUST_CORE_MAKEFILE = 
LIBRETRO_MEDNAFEN_SUPAFAUST_CORE_BUILD_PATH = 
LIBRETRO_MEDNAFEN_SUPAFAUST_CORE_OUTPUT_NAME = mednafen_supafaust_libretro.so
LIBRETRO_MEDNAFEN_SUPAFAUST_CORE_PLATFORM = unix
LIBRETRO_MEDNAFEN_SUPAFAUST_CORE_EXTRA_VARS = 

define LIBRETRO_MEDNAFEN_SUPAFAUST_BUILD_CMDS
	$(TARGET_MAKE_ENV) env -u GIT_DIR $(MAKE1) -f $(LIBRETRO_MEDNAFEN_SUPAFAUST_BUILD_HELPER) \
		WORKDIR="$(LIBRETRO_MEDNAFEN_SUPAFAUST_CORES_WORKDIR)" \
		PATCH_DIR="$(@D)/patches" \
		CORE_NAME="$(LIBRETRO_MEDNAFEN_SUPAFAUST_CORE_NAME)" \
		CORE_REPO="$(LIBRETRO_MEDNAFEN_SUPAFAUST_CORE_REPO)" \
		CORE_BRANCH="$(LIBRETRO_MEDNAFEN_SUPAFAUST_CORE_BRANCH)" \
		CORE_HASH="$(LIBRETRO_MEDNAFEN_SUPAFAUST_CORE_HASH)" \
		CORE_MAKEFILE="$(LIBRETRO_MEDNAFEN_SUPAFAUST_CORE_MAKEFILE)" \
		CORE_BUILD_PATH="$(LIBRETRO_MEDNAFEN_SUPAFAUST_CORE_BUILD_PATH)" \
		CORE_OUTPUT_NAME="$(LIBRETRO_MEDNAFEN_SUPAFAUST_CORE_OUTPUT_NAME)" \
		CORE_PLATFORM="$(LIBRETRO_MEDNAFEN_SUPAFAUST_CORE_PLATFORM)" \
		CORE_EXTRA_VARS="$(LIBRETRO_MEDNAFEN_SUPAFAUST_CORE_EXTRA_VARS)" \
		CC="$(TARGET_CC)" \
		CXX="$(TARGET_CXX)" \
		AR="$(TARGET_AR)" \
		RANLIB="$(TARGET_RANLIB)" \
		CROSS_COMPILE="$(TARGET_CROSS)" \
		build
endef
define LIBRETRO_MEDNAFEN_SUPAFAUST_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 0755 \
		$(LIBRETRO_MEDNAFEN_SUPAFAUST_CORES_WORKDIR)/output/mednafen_supafaust_libretro.so \
		$(TARGET_DIR)$(LIBRETRO_MEDNAFEN_SUPAFAUST_CORES_INSTALL_DIR)/mednafen_supafaust_libretro.so
endef

$(eval $(generic-package))
