################################################################################
# libretro-pcsx-rearmed
################################################################################

LIBRETRO_PCSX_REARMED_VERSION = local
LIBRETRO_PCSX_REARMED_SITE = $(BR2_EXTERNAL_ALLIUM_EXTERNAL_PATH)/package/libretro-pcsx-rearmed
LIBRETRO_PCSX_REARMED_SITE_METHOD = local
LIBRETRO_PCSX_REARMED_LICENSE = See upstream

LIBRETRO_PCSX_REARMED_CORES_WORKDIR = $(@D)/core-build
LIBRETRO_PCSX_REARMED_CORES_INSTALL_DIR = /usr/lib/minui/cores

LIBRETRO_PCSX_REARMED_BUILD_HELPER = $(BR2_EXTERNAL_ALLIUM_EXTERNAL_PATH)/package/allium-support/libretro-core.mkfrag
LIBRETRO_PCSX_REARMED_CORE_NAME = pcsx_rearmed
LIBRETRO_PCSX_REARMED_CORE_REPO = 
LIBRETRO_PCSX_REARMED_CORE_BRANCH = 
LIBRETRO_PCSX_REARMED_CORE_HASH = 
LIBRETRO_PCSX_REARMED_CORE_MAKEFILE = Makefile.libretro
LIBRETRO_PCSX_REARMED_CORE_BUILD_PATH = 
LIBRETRO_PCSX_REARMED_CORE_OUTPUT_NAME = pcsx_rearmed_libretro.so
LIBRETRO_PCSX_REARMED_CORE_PLATFORM = h5
LIBRETRO_PCSX_REARMED_CORE_EXTRA_VARS = 

define LIBRETRO_PCSX_REARMED_BUILD_CMDS
	$(TARGET_MAKE_ENV) env -u GIT_DIR $(MAKE1) -f $(LIBRETRO_PCSX_REARMED_BUILD_HELPER) \
		WORKDIR="$(LIBRETRO_PCSX_REARMED_CORES_WORKDIR)" \
		PATCH_DIR="$(@D)/patches" \
		CORE_NAME="$(LIBRETRO_PCSX_REARMED_CORE_NAME)" \
		CORE_REPO="$(LIBRETRO_PCSX_REARMED_CORE_REPO)" \
		CORE_BRANCH="$(LIBRETRO_PCSX_REARMED_CORE_BRANCH)" \
		CORE_HASH="$(LIBRETRO_PCSX_REARMED_CORE_HASH)" \
		CORE_MAKEFILE="$(LIBRETRO_PCSX_REARMED_CORE_MAKEFILE)" \
		CORE_BUILD_PATH="$(LIBRETRO_PCSX_REARMED_CORE_BUILD_PATH)" \
		CORE_OUTPUT_NAME="$(LIBRETRO_PCSX_REARMED_CORE_OUTPUT_NAME)" \
		CORE_PLATFORM="$(LIBRETRO_PCSX_REARMED_CORE_PLATFORM)" \
		CORE_EXTRA_VARS="$(LIBRETRO_PCSX_REARMED_CORE_EXTRA_VARS)" \
		CC="$(TARGET_CC)" \
		CXX="$(TARGET_CXX)" \
		AR="$(TARGET_AR)" \
		RANLIB="$(TARGET_RANLIB)" \
		CROSS_COMPILE="$(TARGET_CROSS)" \
		build
endef
define LIBRETRO_PCSX_REARMED_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 0755 \
		$(LIBRETRO_PCSX_REARMED_CORES_WORKDIR)/output/pcsx_rearmed_libretro.so \
		$(TARGET_DIR)$(LIBRETRO_PCSX_REARMED_CORES_INSTALL_DIR)/pcsx_rearmed_libretro.so
endef

$(eval $(generic-package))
