################################################################################
# libretro-gambatte
################################################################################

LIBRETRO_GAMBATTE_VERSION = local
LIBRETRO_GAMBATTE_SITE = $(BR2_EXTERNAL_ALLIUM_EXTERNAL_PATH)/package/libretro-gambatte
LIBRETRO_GAMBATTE_SITE_METHOD = local
LIBRETRO_GAMBATTE_LICENSE = See upstream

LIBRETRO_GAMBATTE_CORES_WORKDIR = $(@D)/core-build
LIBRETRO_GAMBATTE_CORES_INSTALL_DIR = /usr/lib/minui/cores

LIBRETRO_GAMBATTE_BUILD_HELPER = $(BR2_EXTERNAL_ALLIUM_EXTERNAL_PATH)/package/allium-support/libretro-core.mkfrag
LIBRETRO_GAMBATTE_CORE_NAME = gambatte
LIBRETRO_GAMBATTE_CORE_REPO = https://github.com/libretro/gambatte-libretro
LIBRETRO_GAMBATTE_CORE_BRANCH = 
LIBRETRO_GAMBATTE_CORE_HASH = 
LIBRETRO_GAMBATTE_CORE_MAKEFILE = Makefile.libretro
LIBRETRO_GAMBATTE_CORE_BUILD_PATH = 
LIBRETRO_GAMBATTE_CORE_OUTPUT_NAME = gambatte_libretro.so
LIBRETRO_GAMBATTE_CORE_PLATFORM = unix
LIBRETRO_GAMBATTE_CORE_EXTRA_VARS = 

define LIBRETRO_GAMBATTE_BUILD_CMDS
	$(TARGET_MAKE_ENV) env -u GIT_DIR $(MAKE1) -f $(LIBRETRO_GAMBATTE_BUILD_HELPER) \
		WORKDIR="$(LIBRETRO_GAMBATTE_CORES_WORKDIR)" \
		PATCH_DIR="$(@D)/patches" \
		CORE_NAME="$(LIBRETRO_GAMBATTE_CORE_NAME)" \
		CORE_REPO="$(LIBRETRO_GAMBATTE_CORE_REPO)" \
		CORE_BRANCH="$(LIBRETRO_GAMBATTE_CORE_BRANCH)" \
		CORE_HASH="$(LIBRETRO_GAMBATTE_CORE_HASH)" \
		CORE_MAKEFILE="$(LIBRETRO_GAMBATTE_CORE_MAKEFILE)" \
		CORE_BUILD_PATH="$(LIBRETRO_GAMBATTE_CORE_BUILD_PATH)" \
		CORE_OUTPUT_NAME="$(LIBRETRO_GAMBATTE_CORE_OUTPUT_NAME)" \
		CORE_PLATFORM="$(LIBRETRO_GAMBATTE_CORE_PLATFORM)" \
		CORE_EXTRA_VARS="$(LIBRETRO_GAMBATTE_CORE_EXTRA_VARS)" \
		CC="$(TARGET_CC)" \
		CXX="$(TARGET_CXX)" \
		AR="$(TARGET_AR)" \
		RANLIB="$(TARGET_RANLIB)" \
		CROSS_COMPILE="$(TARGET_CROSS)" \
		build
endef
define LIBRETRO_GAMBATTE_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 0755 \
		$(LIBRETRO_GAMBATTE_CORES_WORKDIR)/output/gambatte_libretro.so \
		$(TARGET_DIR)$(LIBRETRO_GAMBATTE_CORES_INSTALL_DIR)/gambatte_libretro.so
endef

$(eval $(generic-package))
