################################################################################
# libretro-pokemini
################################################################################

LIBRETRO_POKEMINI_VERSION = local
LIBRETRO_POKEMINI_SITE = $(BR2_EXTERNAL_ALLIUM_EXTERNAL_PATH)/package/libretro-pokemini
LIBRETRO_POKEMINI_SITE_METHOD = local
LIBRETRO_POKEMINI_LICENSE = See upstream

LIBRETRO_POKEMINI_CORES_WORKDIR = $(@D)/core-build
LIBRETRO_POKEMINI_CORES_INSTALL_DIR = /usr/lib/minui/cores

LIBRETRO_POKEMINI_BUILD_HELPER = $(BR2_EXTERNAL_ALLIUM_EXTERNAL_PATH)/package/allium-support/libretro-core.mkfrag
LIBRETRO_POKEMINI_CORE_NAME = pokemini
LIBRETRO_POKEMINI_CORE_REPO = https://github.com/libretro/PokeMini
LIBRETRO_POKEMINI_CORE_BRANCH = 
LIBRETRO_POKEMINI_CORE_HASH = 
LIBRETRO_POKEMINI_CORE_MAKEFILE = 
LIBRETRO_POKEMINI_CORE_BUILD_PATH = 
LIBRETRO_POKEMINI_CORE_OUTPUT_NAME = pokemini_libretro.so
LIBRETRO_POKEMINI_CORE_PLATFORM = unix
LIBRETRO_POKEMINI_CORE_EXTRA_VARS = 

define LIBRETRO_POKEMINI_BUILD_CMDS
	$(TARGET_MAKE_ENV) env -u GIT_DIR $(MAKE1) -f $(LIBRETRO_POKEMINI_BUILD_HELPER) \
		WORKDIR="$(LIBRETRO_POKEMINI_CORES_WORKDIR)" \
		PATCH_DIR="$(@D)/patches" \
		CORE_NAME="$(LIBRETRO_POKEMINI_CORE_NAME)" \
		CORE_REPO="$(LIBRETRO_POKEMINI_CORE_REPO)" \
		CORE_BRANCH="$(LIBRETRO_POKEMINI_CORE_BRANCH)" \
		CORE_HASH="$(LIBRETRO_POKEMINI_CORE_HASH)" \
		CORE_MAKEFILE="$(LIBRETRO_POKEMINI_CORE_MAKEFILE)" \
		CORE_BUILD_PATH="$(LIBRETRO_POKEMINI_CORE_BUILD_PATH)" \
		CORE_OUTPUT_NAME="$(LIBRETRO_POKEMINI_CORE_OUTPUT_NAME)" \
		CORE_PLATFORM="$(LIBRETRO_POKEMINI_CORE_PLATFORM)" \
		CORE_EXTRA_VARS="$(LIBRETRO_POKEMINI_CORE_EXTRA_VARS)" \
		CC="$(TARGET_CC)" \
		CXX="$(TARGET_CXX)" \
		AR="$(TARGET_AR)" \
		RANLIB="$(TARGET_RANLIB)" \
		CROSS_COMPILE="$(TARGET_CROSS)" \
		build
endef
define LIBRETRO_POKEMINI_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 0755 \
		$(LIBRETRO_POKEMINI_CORES_WORKDIR)/output/pokemini_libretro.so \
		$(TARGET_DIR)$(LIBRETRO_POKEMINI_CORES_INSTALL_DIR)/pokemini_libretro.so
endef

$(eval $(generic-package))
