################################################################################
# libretro-race
################################################################################

LIBRETRO_RACE_VERSION = local
LIBRETRO_RACE_SITE = $(BR2_EXTERNAL_ALLIUM_EXTERNAL_PATH)/package/libretro-race
LIBRETRO_RACE_SITE_METHOD = local
LIBRETRO_RACE_LICENSE = See upstream

LIBRETRO_RACE_CORES_WORKDIR = $(@D)/core-build
LIBRETRO_RACE_CORES_INSTALL_DIR = /usr/lib/minui/cores

LIBRETRO_RACE_BUILD_HELPER = $(BR2_EXTERNAL_ALLIUM_EXTERNAL_PATH)/package/allium-support/libretro-core.mkfrag
LIBRETRO_RACE_CORE_NAME = race
LIBRETRO_RACE_CORE_REPO = 
LIBRETRO_RACE_CORE_BRANCH = 
LIBRETRO_RACE_CORE_HASH = 
LIBRETRO_RACE_CORE_MAKEFILE = 
LIBRETRO_RACE_CORE_BUILD_PATH = 
LIBRETRO_RACE_CORE_OUTPUT_NAME = race_libretro.so
LIBRETRO_RACE_CORE_PLATFORM = unix
LIBRETRO_RACE_CORE_EXTRA_VARS = 

define LIBRETRO_RACE_BUILD_CMDS
	$(TARGET_MAKE_ENV) env -u GIT_DIR $(MAKE1) -f $(LIBRETRO_RACE_BUILD_HELPER) \
		WORKDIR="$(LIBRETRO_RACE_CORES_WORKDIR)" \
		PATCH_DIR="$(@D)/patches" \
		CORE_NAME="$(LIBRETRO_RACE_CORE_NAME)" \
		CORE_REPO="$(LIBRETRO_RACE_CORE_REPO)" \
		CORE_BRANCH="$(LIBRETRO_RACE_CORE_BRANCH)" \
		CORE_HASH="$(LIBRETRO_RACE_CORE_HASH)" \
		CORE_MAKEFILE="$(LIBRETRO_RACE_CORE_MAKEFILE)" \
		CORE_BUILD_PATH="$(LIBRETRO_RACE_CORE_BUILD_PATH)" \
		CORE_OUTPUT_NAME="$(LIBRETRO_RACE_CORE_OUTPUT_NAME)" \
		CORE_PLATFORM="$(LIBRETRO_RACE_CORE_PLATFORM)" \
		CORE_EXTRA_VARS="$(LIBRETRO_RACE_CORE_EXTRA_VARS)" \
		CC="$(TARGET_CC)" \
		CXX="$(TARGET_CXX)" \
		AR="$(TARGET_AR)" \
		RANLIB="$(TARGET_RANLIB)" \
		CROSS_COMPILE="$(TARGET_CROSS)" \
		build
endef
define LIBRETRO_RACE_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 0755 \
		$(LIBRETRO_RACE_CORES_WORKDIR)/output/race_libretro.so \
		$(TARGET_DIR)$(LIBRETRO_RACE_CORES_INSTALL_DIR)/race_libretro.so
endef

$(eval $(generic-package))
