################################################################################
# libretro-snes9x2005-plus
################################################################################

LIBRETRO_SNES9X2005_PLUS_VERSION = local
LIBRETRO_SNES9X2005_PLUS_SITE = $(BR2_EXTERNAL_ALLIUM_EXTERNAL_PATH)/package/libretro-snes9x2005-plus
LIBRETRO_SNES9X2005_PLUS_SITE_METHOD = local
LIBRETRO_SNES9X2005_PLUS_LICENSE = See upstream

LIBRETRO_SNES9X2005_PLUS_CORES_WORKDIR = $(@D)/core-build
LIBRETRO_SNES9X2005_PLUS_CORES_INSTALL_DIR = /usr/lib/minui/cores

LIBRETRO_SNES9X2005_PLUS_BUILD_HELPER = $(BR2_EXTERNAL_ALLIUM_EXTERNAL_PATH)/package/allium-support/libretro-core.mkfrag
LIBRETRO_SNES9X2005_PLUS_CORE_NAME = snes9x2005_plus
LIBRETRO_SNES9X2005_PLUS_CORE_REPO = https://github.com/libretro/snes9x2005
LIBRETRO_SNES9X2005_PLUS_CORE_BRANCH = 
LIBRETRO_SNES9X2005_PLUS_CORE_HASH = 
LIBRETRO_SNES9X2005_PLUS_CORE_MAKEFILE = 
LIBRETRO_SNES9X2005_PLUS_CORE_BUILD_PATH = 
LIBRETRO_SNES9X2005_PLUS_CORE_OUTPUT_NAME = snes9x2005_plus_libretro.so
LIBRETRO_SNES9X2005_PLUS_CORE_PLATFORM = unix
LIBRETRO_SNES9X2005_PLUS_CORE_EXTRA_VARS = USE_BLARGG_APU=1

define LIBRETRO_SNES9X2005_PLUS_BUILD_CMDS
	$(TARGET_MAKE_ENV) env -u GIT_DIR $(MAKE1) -f $(LIBRETRO_SNES9X2005_PLUS_BUILD_HELPER) \
		WORKDIR="$(LIBRETRO_SNES9X2005_PLUS_CORES_WORKDIR)" \
		PATCH_DIR="$(@D)/patches" \
		CORE_NAME="$(LIBRETRO_SNES9X2005_PLUS_CORE_NAME)" \
		CORE_REPO="$(LIBRETRO_SNES9X2005_PLUS_CORE_REPO)" \
		CORE_BRANCH="$(LIBRETRO_SNES9X2005_PLUS_CORE_BRANCH)" \
		CORE_HASH="$(LIBRETRO_SNES9X2005_PLUS_CORE_HASH)" \
		CORE_MAKEFILE="$(LIBRETRO_SNES9X2005_PLUS_CORE_MAKEFILE)" \
		CORE_BUILD_PATH="$(LIBRETRO_SNES9X2005_PLUS_CORE_BUILD_PATH)" \
		CORE_OUTPUT_NAME="$(LIBRETRO_SNES9X2005_PLUS_CORE_OUTPUT_NAME)" \
		CORE_PLATFORM="$(LIBRETRO_SNES9X2005_PLUS_CORE_PLATFORM)" \
		CORE_EXTRA_VARS="$(LIBRETRO_SNES9X2005_PLUS_CORE_EXTRA_VARS)" \
		CC="$(TARGET_CC)" \
		CXX="$(TARGET_CXX)" \
		AR="$(TARGET_AR)" \
		RANLIB="$(TARGET_RANLIB)" \
		CROSS_COMPILE="$(TARGET_CROSS)" \
		build
endef
define LIBRETRO_SNES9X2005_PLUS_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 0755 \
		$(LIBRETRO_SNES9X2005_PLUS_CORES_WORKDIR)/output/snes9x2005_plus_libretro.so \
		$(TARGET_DIR)$(LIBRETRO_SNES9X2005_PLUS_CORES_INSTALL_DIR)/snes9x2005_plus_libretro.so
endef

$(eval $(generic-package))
