################################################################################
# libretro-fceumm
################################################################################

LIBRETRO_FCEUMM_VERSION = local
LIBRETRO_FCEUMM_SITE = $(BR2_EXTERNAL_ALLIUM_EXTERNAL_PATH)/package/libretro-fceumm
LIBRETRO_FCEUMM_SITE_METHOD = local
LIBRETRO_FCEUMM_LICENSE = See upstream

LIBRETRO_FCEUMM_CORES_WORKDIR = $(@D)/core-build
LIBRETRO_FCEUMM_CORES_INSTALL_DIR = /usr/lib/minui/cores

LIBRETRO_FCEUMM_BUILD_HELPER = $(BR2_EXTERNAL_ALLIUM_EXTERNAL_PATH)/package/allium-support/libretro-core.mkfrag
LIBRETRO_FCEUMM_CORE_NAME = fceumm
LIBRETRO_FCEUMM_CORE_REPO = https://github.com/libretro/libretro-fceumm
LIBRETRO_FCEUMM_CORE_BRANCH = 
LIBRETRO_FCEUMM_CORE_HASH = 
LIBRETRO_FCEUMM_CORE_MAKEFILE = 
LIBRETRO_FCEUMM_CORE_BUILD_PATH = 
LIBRETRO_FCEUMM_CORE_OUTPUT_NAME = fceumm_libretro.so
LIBRETRO_FCEUMM_CORE_PLATFORM = unix
LIBRETRO_FCEUMM_CORE_EXTRA_VARS = 

define LIBRETRO_FCEUMM_BUILD_CMDS
	$(TARGET_MAKE_ENV) env -u GIT_DIR $(MAKE1) -f $(LIBRETRO_FCEUMM_BUILD_HELPER) \
		WORKDIR="$(LIBRETRO_FCEUMM_CORES_WORKDIR)" \
		PATCH_DIR="$(@D)/patches" \
		CORE_NAME="$(LIBRETRO_FCEUMM_CORE_NAME)" \
		CORE_REPO="$(LIBRETRO_FCEUMM_CORE_REPO)" \
		CORE_BRANCH="$(LIBRETRO_FCEUMM_CORE_BRANCH)" \
		CORE_HASH="$(LIBRETRO_FCEUMM_CORE_HASH)" \
		CORE_MAKEFILE="$(LIBRETRO_FCEUMM_CORE_MAKEFILE)" \
		CORE_BUILD_PATH="$(LIBRETRO_FCEUMM_CORE_BUILD_PATH)" \
		CORE_OUTPUT_NAME="$(LIBRETRO_FCEUMM_CORE_OUTPUT_NAME)" \
		CORE_PLATFORM="$(LIBRETRO_FCEUMM_CORE_PLATFORM)" \
		CORE_EXTRA_VARS="$(LIBRETRO_FCEUMM_CORE_EXTRA_VARS)" \
		CC="$(TARGET_CC)" \
		CXX="$(TARGET_CXX)" \
		AR="$(TARGET_AR)" \
		RANLIB="$(TARGET_RANLIB)" \
		CROSS_COMPILE="$(TARGET_CROSS)" \
		WANT_32BPP=0 \
		build
endef
define LIBRETRO_FCEUMM_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 0755 \
		$(LIBRETRO_FCEUMM_CORES_WORKDIR)/output/fceumm_libretro.so \
		$(TARGET_DIR)$(LIBRETRO_FCEUMM_CORES_INSTALL_DIR)/fceumm_libretro.so
endef

$(eval $(generic-package))
